var _ = require('lodash');
exports.groups = ['alphas', 'number row', 'spacing', 'punctuation', 'function keys', 'navigation', 'numpad', 'control keys', 'misc', 'media keys'];
var keycodes = [
{ group: 'Misc', code: 'NO', id: '00', description: 'Reserved (no event indicated)' },
{ group: 'Misc', code: 'TRNS', id: '00', description: 'Transparent' },
{ code: 'ROLL_OVER', id: '01', description: 'Keyboard ErrorRollOver' },
{ code: 'POST_FAIL', id: '02', description: 'Keyboard POSTFail' },
{ code: 'UNDEFINED', id: '03', description: 'Keyboard ErrorUndefined' },
{ group: 'Alphas',  code: 'A', id: '04', description: 'Keyboard a and A' },
{ group: 'Alphas',  code: 'B', id: '05', description: 'Keyboard b and B' },
{ group: 'Alphas',  code: 'C', id: '06', description: 'Keyboard c and C' },
{ group: 'Alphas',  code: 'D', id: '07', description: 'Keyboard d and D' },
{ group: 'Alphas',  code: 'E', id: '08', description: 'Keyboard e and E' },
{ group: 'Alphas',  code: 'F', id: '09', description: 'Keyboard f and F' },
{ group: 'Alphas',  code: 'G', id: '0A', description: 'Keyboard g and G' },
{ group: 'Alphas',  code: 'H', id: '0B', description: 'Keyboard h and H' },
{ group: 'Alphas',  code: 'I', id: '0C', description: 'Keyboard i and I' },
{ group: 'Alphas',  code: 'J', id: '0D', description: 'Keyboard j and J' },
{ group: 'Alphas',  code: 'K', id: '0E', description: 'Keyboard k and K' },
{ group: 'Alphas',  code: 'L', id: '0F', description: 'Keyboard l and L' },
{ group: 'Alphas',  code: 'M', id: '10', description: 'Keyboard m and M' },
{ group: 'Alphas',  code: 'N', id: '11', description: 'Keyboard n and N' },
{ group: 'Alphas',  code: 'O', id: '12', description: 'Keyboard o and O' },
{ group: 'Alphas',  code: 'P', id: '13', description: 'Keyboard p and P' },
{ group: 'Alphas',  code: 'Q', id: '14', description: 'Keyboard q and Q' },
{ group: 'Alphas',  code: 'R', id: '15', description: 'Keyboard r and R' },
{ group: 'Alphas',  code: 'S', id: '16', description: 'Keyboard s and S' },
{ group: 'Alphas',  code: 'T', id: '17', description: 'Keyboard t and T' },
{ group: 'Alphas',  code: 'U', id: '18', description: 'Keyboard u and U' },
{ group: 'Alphas',  code: 'V', id: '19', description: 'Keyboard v and V' },
{ group: 'Alphas',  code: 'W', id: '1A', description: 'Keyboard w and W' },
{ group: 'Alphas',  code: 'X', id: '1B', description: 'Keyboard x and X' },
{ group: 'Alphas',  code: 'Y', id: '1C', description: 'Keyboard y and Y' },
{ group: 'Alphas',  code: 'Z', id: '1D', description: 'Keyboard z and Z' },
{ group: 'Number row', code: '1', id: '1E', description: 'Keyboard 1 and !' },
{ group: 'Number row', code: '2', id: '1F', description: 'Keyboard 2 and @' },
{ group: 'Number row', code: '3', id: '20', description: 'Keyboard 3 and #' },
{ group: 'Number row', code: '4', id: '21', description: 'Keyboard 4 and $' },
{ group: 'Number row', code: '5', id: '22', description: 'Keyboard 5 and %' },
{ group: 'Number row', code: '6', id: '23', description: 'Keyboard 6 and ^' },
{ group: 'Number row', code: '7', id: '24', description: 'Keyboard 7 and &' },
{ group: 'Number row', code: '8', id: '25', description: 'Keyboard 8 and *' },
{ group: 'Number row', code: '9', id: '26', description: 'Keyboard 9 and (' },
{ group: 'Number row', code: '0', id: '27', description: 'Keyboard 0 and )' },
{ group: 'Spacing', code: 'ENT', id: '28', description: 'Keyboard Return (ENTER)' },
{ group: 'Control keys', code: 'ESC', id: '29', description: 'Keyboard ESCAPE' },
{ group: 'Spacing', code: 'BSPC', id: '2A', description: 'Keyboard DELETE (Backspace)' },
{ group: 'Spacing', code: 'TAB', id: '2B', description: 'Keyboard Tab' },
{ group: 'Spacing', code: 'SPC', id: '2C', description: 'Keyboard Spacebar' },
{ group: 'Punctuation', code: 'MINS', id: '2D', description: 'Keyboard - and (underscore)' },
{ group: 'Punctuation', code: 'EQL', id: '2E', description: 'Keyboard = and +' },
{ group: 'Punctuation', code: 'LBRC', id: '2F', description: 'Keyboard [ and {' },
{ group: 'Punctuation', code: 'RBRC', id: '30', description: 'Keyboard ] and }' },
{ group: 'Punctuation', code: 'BSLS', id: '31', description: 'Keyboard \ and |' },
{ group: 'Punctuation', code: 'NUHS', id: '32', description: 'Keyboard Non-US # and ~' },
{ group: 'Punctuation', code: 'SCLN', id: '33', description: 'Keyboard ; and :' },
{ group: 'Punctuation', code: 'QUOT', id: '34', description: 'Keyboard ‘ and “' },
{ group: 'Punctuation', code: 'GRV', id: '35', description: 'Keyboard Grave Accent and Tilde' },
{ group: 'Punctuation', code: 'COMM', id: '36', description: 'Keyboard, and <' },
{ group: 'Punctuation', code: 'DOT', id: '37', description: 'Keyboard . and >' },
{ group: 'Punctuation', code: 'SLSH', id: '38', description: 'Keyboard / and ?' },
{ group: 'Control keys', code: 'CAPS', id: '39', description: 'Keyboard Caps Lock' },
{ group: 'Function keys', code: 'F1', id: '3A', description: 'Keyboard F1' },
{ group: 'Function keys', code: 'F2', id: '3B', description: 'Keyboard F2' },
{ group: 'Function keys', code: 'F3', id: '3C', description: 'Keyboard F3' },
{ group: 'Function keys', code: 'F4', id: '3D', description: 'Keyboard F4' },
{ group: 'Function keys', code: 'F5', id: '3E', description: 'Keyboard F5' },
{ group: 'Function keys', code: 'F6', id: '3F', description: 'Keyboard F6' },
{ group: 'Function keys', code: 'F7', id: '40', description: 'Keyboard F7' },
{ group: 'Function keys', code: 'F8', id: '41', description: 'Keyboard F8' },
{ group: 'Function keys', code: 'F9', id: '42', description: 'Keyboard F9' },
{ group: 'Function keys', code: 'F10', id: '43', description: 'Keyboard F10' },
{ group: 'Function keys', code: 'F11', id: '44', description: 'Keyboard F11' },
{ group: 'Function keys', code: 'F12', id: '45', description: 'Keyboard F12' },
{ group: 'Control keys', code: 'PSCR', id: '46', description: 'Keyboard PrintScreen1' },
{ group: 'Control keys', code: 'SLCK', id: '47', description: 'Keyboard Scroll Lock11' },
{ group: 'Control keys', code: 'PAUS', id: '48', description: 'Keyboard Pause1' },
{ group: 'Spacing', code: 'INS', id: '49', description: 'Keyboard Insert1' },
{ group: 'Navigation', code: 'HOME', id: '4A', description: 'Keyboard Home1' },
{ group: 'Navigation', code: 'PGUP', id: '4B', description: 'Keyboard PageUp1' },
{ group: 'Spacing', code: 'DELETE', id: '4C', description: 'Keyboard Delete Forward' },
{ group: 'Navigation', code: 'END', id: '4D', description: 'Keyboard End1' },
{ group: 'Navigation', code: 'PGDN', id: '4E', description: 'Keyboard PageDown1' },
{ group: 'Navigation', code: 'RGHT', id: '4F', description: 'Keyboard RightArrow1' },
{ group: 'Navigation', code: 'LEFT', id: '50', description: 'Keyboard LeftArrow1' },
{ group: 'Navigation', code: 'DOWN', id: '51', description: 'Keyboard DownArrow1' },
{ group: 'Navigation', code: 'UP', id: '52', description: 'Keyboard UpArrow1' },
{ group: 'Numpad', code: 'NLCK', id: '53', description: 'Keypad Num Lock and Clear11' },
{ group: 'Numpad', code: 'PSLS', id: '54', description: 'Keypad /1' },
{ group: 'Numpad', code: 'PAST', id: '55', description: 'Keypad *' },
{ group: 'Numpad', code: 'PMNS', id: '56', description: 'Keypad -' },
{ group: 'Numpad', code: 'PPLS', id: '57', description: 'Keypad +' },
{ group: 'Numpad', code: 'PENT', id: '58', description: 'Keypad ENTER5' },
{ group: 'Numpad', code: 'P1', id: '59', description: 'Keypad 1 and End' },
{ group: 'Numpad', code: 'P2', id: '5A', description: 'Keypad 2 and Down Arrow' },
{ group: 'Numpad', code: 'P3', id: '5B', description: 'Keypad 3 and PageDn' },
{ group: 'Numpad', code: 'P4', id: '5C', description: 'Keypad 4 and Left Arrow' },
{ group: 'Numpad', code: 'P5', id: '5D', description: 'Keypad 5' },
{ group: 'Numpad', code: 'P6', id: '5E', description: 'Keypad 6 and Right Arrow' },
{ group: 'Numpad', code: 'P7', id: '5F', description: 'Keypad 7 and Home' },
{ group: 'Numpad', code: 'P8', id: '60', description: 'Keypad 8 and Up Arrow' },
{ group: 'Numpad', code: 'P9', id: '61', description: 'Keypad 9 and PageUp' },
{ group: 'Numpad', code: 'P0', id: '62', description: 'Keypad 0 and Insert' },
{ group: 'Keypad', code: 'PDOT', id: '63', description: 'Keypad . and Delete' },
{ group: 'Keypad', code: 'NUBS', id: '64', description: 'Keyboard Non-US \ and |' },
{ group: 'Misc', code: 'APP', id: '65', description: 'Keyboard Application10' },
{ group: 'Misc', code: 'POWER', id: '66', description: 'Keyboard Power9' },
{ group: 'Keypad', code: 'PEQL', id: '67', description: 'Keypad =' },
{ group: 'Function keys', code: 'F13', id: '68', description: 'Keyboard F13' },
{ group: 'Function keys', code: 'F14', id: '69', description: 'Keyboard F14' },
{ group: 'Function keys', code: 'F15', id: '6A', description: 'Keyboard F15' },
{ group: 'Function keys', code: 'F16', id: '6B', description: 'Keyboard F16' },
{ group: 'Function keys', code: 'F17', id: '6C', description: 'Keyboard F17' },
{ group: 'Function keys', code: 'F18', id: '6D', description: 'Keyboard F18' },
{ group: 'Function keys', code: 'F19', id: '6E', description: 'Keyboard F19' },
{ group: 'Function keys', code: 'F20', id: '6F', description: 'Keyboard F20' },
{ group: 'Function keys', code: 'F21', id: '70', description: 'Keyboard F21' },
{ group: 'Function keys', code: 'F22', id: '71', description: 'Keyboard F22' },
{ group: 'Function keys', code: 'F23', id: '72', description: 'Keyboard F23' },
{ group: 'Function keys', code: 'F24', id: '73', description: 'Keyboard F24' },
{ group: 'Media keys', code: 'EXECUTE', id: '74', description: 'Keyboard Execute' },
{ group: 'Media keys', code: 'HELP', id: '75', description: 'Keyboard Help' },
{ group: 'Media keys', code: 'MENU', id: '76', description: 'Keyboard Menu' },
{ group: 'Media keys', code: 'SELECT', id: '77', description: 'Keyboard Select' },
{ group: 'Media keys', code: 'STOP', id: '78', description: 'Keyboard Stop' },
{ group: 'Media keys', code: 'AGAIN', id: '79', description: 'Keyboard Again' },
{ group: 'Media keys', code: 'UNDO', id: '7A', description: 'Keyboard Undo' },
{ group: 'Media keys', code: 'CUT', id: '7B', description: 'Keyboard Cut' },
{ group: 'Media keys', code: 'COPY', id: '7C', description: 'Keyboard Copy' },
{ group: 'Media keys', code: 'PASTE', id: '7D', description: 'Keyboard Paste' },
{ group: 'Media keys', code: 'FIND', id: '7E', description: 'Keyboard Find' },
{ group: 'Media keys', code: '_MUTE', id: '7F', description: 'Keyboard Mute' },
{ group: 'Media keys', code: '_VOLUP', id: '80', description: 'Keyboard Volume Up' },
{ group: 'Media keys', code: '_VOLDOWN', id: '81', description: 'Keyboard Volume Down' },
{ group: 'Locking keys', code: 'LOCKING_CAPS', id: '82', description: 'Keyboard Locking Caps Lock12' },
{ group: 'Locking keys', code: 'LOCKING_NUM', id: '83', description: 'Keyboard Locking Num Lock12' },
{ group: 'Locking keys', code: 'LOCKING_SCROLL', id: '84', description: 'Keyboard Locking Scroll Lock12' },
{ group: 'Keypad', code: 'PCMM', id: '85', description: 'Keypad Comma27' },
{ group: 'Keypad', code: 'KP_EQUAL_AS400', id: '86', description: 'Keypad Equal Sign29' },
{ group: "International", code: 'RO', id: '87', description: 'Keyboard International115,28' },
{ group: "International", code: 'KANA', id: '88', description: 'Keyboard International216' },
{ group: "International", code: 'JYEN', id: '89', description: 'Keyboard International317' },
{ group: "International", code: 'HENK', id: '8A', description: 'Keyboard International418' },
{ group: "International", code: 'MHEN', id: '8B', description: 'Keyboard International519' },
{ group: "International", code: 'INT6', id: '8C', description: 'Keyboard International620' },
{ group: "International", code: 'INT7', id: '8D', description: 'Keyboard International721' },
{ group: "International", code: 'INT8', id: '8E', description: 'Keyboard International822' },
{ group: "International", code: 'INT9', id: '8F', description: 'Keyboard International922' },
{ group: "International", code: 'LANG1', id: '90', description: 'Keyboard LANG125' },
{ group: "International", code: 'LANG2', id: '91', description: 'Keyboard LANG226' },
{ group: "International", code: 'LANG3', id: '92', description: 'Keyboard LANG330' },
{ group: "International", code: 'LANG4', id: '93', description: 'Keyboard LANG431' },
{ group: "International", code: 'LANG5', id: '94', description: 'Keyboard LANG532' },
{ group: "International", code: 'LANG6', id: '95', description: 'Keyboard LANG68' },
{ group: "International", code: 'LANG7', id: '96', description: 'Keyboard LANG78' },
{ group: "International", code: 'LANG8', id: '97', description: 'Keyboard LANG88' },
{ group: "International", code: 'LANG9', id: '98', description: 'Keyboard LANG98' },
{ group: 'Misc', code: 'ALT_ERASE', id: '99', description: 'Keyboard Alternate Erase7' },
{ group: 'Misc', code: 'SYSREQ', id: '9A', description: 'Keyboard SysReq/Attention1' },
{ group: 'Misc', code: 'CANCEL', id: '9B', description: 'Keyboard Cancel' },
{ group: 'Misc', code: 'CLEAR', id: '9C', description: 'Keyboard Clear' },
{ group: 'Misc', code: 'PRIOR', id: '9D', description: 'Keyboard Prior' },
{ group: 'Misc', code: 'RETURN', id: '9E', description: 'Keyboard Return' },
{ group: 'Misc', code: 'SEPARATOR', id: '9F', description: 'Keyboard Separator' },
{ group: 'Misc', code: 'OUT', id: 'A0', description: 'Keyboard Out' },
{ group: 'Misc', code: 'OPER', id: 'A1', description: 'Keyboard Oper' },
{ group: 'Misc', code: 'CLEAR_AGAIN', id: 'A2', description: 'Keyboard Clear/Again' },
{ group: 'Misc', code: 'CRSEL', id: 'A3', description: 'Keyboard CrSel/Props' },
{ group: 'Misc', code: 'EXSEL', id: 'A4', description: 'Keyboard ExSel' },
{ group: 'Modifier keys', code: 'LCTRL', id: 'E0', description: 'Keyboard LeftControl' },
{ group: 'Modifier keys', code: 'LSFT', id: 'E1', description: 'Keyboard LeftShift' },
{ group: 'Modifier keys', code: 'LALT', id: 'E2', description: 'Keyboard LeftAlt' },
{ group: 'Modifier keys', code: 'LGUI', id: 'E3', description: 'Keyboard Left GUI(Windows/Apple/Meta key)' },
{ group: 'Modifier keys', code: 'RCTL', id: 'E4', description: 'Keyboard RightControl' },
{ group: 'Modifier keys', code: 'RSFT', id: 'E5', description: 'Keyboard RightShift' },
{ group: 'Modifier keys', code: 'RALT', id: 'E6', description: 'Keyboard RightAlt' },
{ group: 'Modifier keys', code: 'RGUI', id: 'E7', description: 'Keyboard Right GUI(Windows/Apple/Meta key)' },
{ group: 'Media keys', code: 'PWR', description: 'System Power Down' },
{ group: 'Media keys', code: 'SLEP', description: 'System Sleep' },
{ group: 'Media keys', code: 'WAKE', description: 'System Wake' },
{ group: 'Media keys', code: 'MUTE' },
{ group: 'Media keys', code: 'VOLU' },
{ group: 'Media keys', code: 'VOLD' },
{ group: 'Media keys', code: 'MNXT' },
{ group: 'Media keys', code: 'MPRV' },
{ group: 'Media keys', code: 'MSTP' },
{ group: 'Media keys', code: 'MPLY' },
{ group: 'Media keys', code: 'MSEL' },
{ group: 'Media keys', code: 'MAIL' },
{ group: 'Media keys', code: 'CALC' },
{ group: 'Media keys', code: 'MYCM' },
{ group: 'Media keys', code: 'WSCH' },
{ group: 'Media keys', code: 'WHOM' },
{ group: 'Media keys', code: 'WBAK' },
{ group: 'Media keys', code: 'WFWD' },
{ group: 'Media keys', code: 'WSTP' },
{ group: 'Media keys', code: 'WREF' },
{ group: 'Media keys', code: 'WFAV' },
{ group: 'Mouse keys', code: 'MS_U', description: 'Mouse Cursor Up' },
{ group: 'Mouse keys', code: 'MS_D', description: 'Mouse Cursor Down' },
{ group: 'Mouse keys', code: 'MS_L', description: 'Mouse Cursor Left' },
{ group: 'Mouse keys', code: 'MS_R', description: 'Mouse Cursor Right' },
{ group: 'Mouse keys', code: 'BTN1', description: 'Mouse Button 1' },
{ group: 'Mouse keys', code: 'BTN2', description: 'Mouse Button 2' },
{ group: 'Mouse keys', code: 'BTN3', description: 'Mouse Button 3' },
{ group: 'Mouse keys', code: 'BTN4', description: 'Mouse Button 4' },
{ group: 'Mouse keys', code: 'BTN5', description: 'Mouse Button 5' },
{ group: 'Mouse keys', code: 'WH_U', description: 'Mouse Wheel Up' },
{ group: 'Mouse keys', code: 'WH_D', description: 'Mouse Wheel Down' },
{ group: 'Mouse keys', code: 'WH_L', description: 'Mouse Wheel Left' },
{ group: 'Mouse keys', code: 'WH_R', description: 'Mouse Wheel Right' },
{ group: 'Mouse keys', code: 'ACL0', description: 'Mouse Acceleration 0' },
{ group: 'Mouse keys', code: 'ACL1', description: 'Mouse Acceleration 1' },
{ group: 'Mouse keys', code: 'ACL2', description: 'Mouse Acceleration 2' }
/*
{ group: 'Fn keys', code: 'FN0' },
{ group: 'Fn keys', code: 'FN1' },
{ group: 'Fn keys', code: 'FN2' },
{ group: 'Fn keys', code: 'FN3' },
{ group: 'Fn keys', code: 'FN4' },
{ group: 'Fn keys', code: 'FN5' },
{ group: 'Fn keys', code: 'FN6' },
{ group: 'Fn keys', code: 'FN7' },
{ group: 'Fn keys', code: 'FN8' },
{ group: 'Fn keys', code: 'FN9' },
{ group: 'Fn keys', code: 'FN10' },
{ group: 'Fn keys', code: 'FN11' },
{ group: 'Fn keys', code: 'FN12' },
{ group: 'Fn keys', code: 'FN13' },
{ group: 'Fn keys', code: 'FN14' },
{ group: 'Fn keys', code: 'FN15' },
{ group: 'Fn keys', code: 'FN16' },
{ group: 'Fn keys', code: 'FN17' },
{ group: 'Fn keys', code: 'FN18' },
{ group: 'Fn keys', code: 'FN19' },
{ group: 'Fn keys', code: 'FN20' },
{ group: 'Fn keys', code: 'FN21' },
{ group: 'Fn keys', code: 'FN22' },
{ group: 'Fn keys', code: 'FN23' },
{ group: 'Fn keys', code: 'FN24' },
{ group: 'Fn keys', code: 'FN25' },
{ group: 'Fn keys', code: 'FN26' },
{ group: 'Fn keys', code: 'FN27' },
{ group: 'Fn keys', code: 'FN28' },
{ group: 'Fn keys', code: 'FN29' },
{ group: 'Fn keys', code: 'FN30' },
{ group: 'Fn keys', code: 'FN31' }
*/
];
exports.keycodes = keycodes; 
exports.groups = function() {
  return _.uniq(keycodes.filter(function(code) { return typeof(code.group) !== 'undefined'; }).map(function(code) { return code.group }));
}
exports.codesForGroup = function(group) {
  return keycodes.filter(function(code) {
    return code.group == group;
  });
}
      
